In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import plotly.express as px

In [8]:
hh_ds = pd.read_csv('data/dst-3.0_16_1_hh_database.csv', sep = ';')
hh_ds.shape[0]

44744

In [4]:
hh_ds.duplicated().sum()

153

In [ ]:
duplicates = hh_ds[hh_ds.duplicated(subset = hh_ds.columns)]

list1 = list(duplicates.index)
list1

In [12]:
list_158 = [380,
 543,
 876,
 1038,
 1116,
 1228,
 1300,
 1362,
 1364,
 1432,
 1651,
 1695,
 1815,
 1838,
 1844,
 2040,
 2052,
 2304,
 2330,
 2567,
 2568,
 2693,
 2710,
 2786,
 2855,
 2930,
 2934,
 2952,
 2993,
 3094,
 3108,
 3199,
 3238,
 3244,
 3252,
 3332,
 3635,
 3646,
 3729,
 3734,
 3764,
 3779,
 3780,
 3790,
 3794,
 3806,
 3853,
 3887,
 3925,
 3950,
 4003,
 4023,
 4085,
 4106,
 4144,
 4189,
 4266,
 4364,
 4426,
 4432,
 4467,
 4468,
 4504,
 4508,
 4540,
 4566,
 4648,
 4657,
 4669,
 4675,
 4717,
 4727,
 4854,
 4970,
 5018,
 5045,
 5051,
 5052,
 5087,
 5110,
 5135,
 5155,
 5200,
 5246,
 5251,
 5254,
 5374,
 5441,
 5480,
 5498,
 5612,
 5615,
 5626,
 5633,
 5660,
 5673,
 5681,
 5700,
 5753,
 5761,
 5764,
 5773,
 5790,
 5796,
 5805,
 5813,
 5824,
 5835,
 5847,
 5881,
 5882,
 5890,
 5914,
 5918,
 5938,
 5942,
 5945,
 5962,
 5969,
 5977,
 5999,
 6025,
 6036,
 6041,
 6057,
 6063,
 6080,
 6117,
 6121,
 6141,
 6189,
 6211,
 6212,
 6213,
 6259,
 6280,
 6283,
 6301,
 6306,
 6329,
 6340,
 6378,
 6405,
 6421,
 6429,
 6440,
 6460,
 6480,
 6506,
 6511,
 6535,
 6541,
 6553,
 25442,
 26877,
 34119,
 37932,
 40081]
list_153 = [380,
 543,
 876,
 1038,
 1116,
 1228,
 1300,
 1362,
 1364,
 1432,
 1651,
 1695,
 1815,
 1838,
 1844,
 2040,
 2052,
 2304,
 2330,
 2567,
 2568,
 2693,
 2710,
 2786,
 2855,
 2930,
 2934,
 2952,
 2993,
 3094,
 3108,
 3199,
 3238,
 3244,
 3252,
 3332,
 3635,
 3646,
 3729,
 3734,
 3764,
 3779,
 3780,
 3790,
 3794,
 3806,
 3853,
 3887,
 3925,
 3950,
 4003,
 4023,
 4085,
 4106,
 4144,
 4189,
 4266,
 4364,
 4426,
 4432,
 4467,
 4468,
 4504,
 4508,
 4540,
 4566,
 4648,
 4657,
 4669,
 4675,
 4717,
 4727,
 4854,
 4970,
 5018,
 5045,
 5051,
 5052,
 5087,
 5110,
 5135,
 5155,
 5200,
 5246,
 5251,
 5254,
 5374,
 5441,
 5480,
 5498,
 5612,
 5615,
 5626,
 5633,
 5660,
 5673,
 5681,
 5700,
 5753,
 5761,
 5764,
 5773,
 5790,
 5796,
 5805,
 5813,
 5824,
 5835,
 5847,
 5881,
 5882,
 5890,
 5914,
 5918,
 5938,
 5942,
 5945,
 5962,
 5969,
 5977,
 5999,
 6025,
 6036,
 6041,
 6057,
 6063,
 6080,
 6117,
 6121,
 6141,
 6189,
 6211,
 6212,
 6213,
 6259,
 6280,
 6283,
 6301,
 6306,
 6329,
 6340,
 6378,
 6405,
 6421,
 6429,
 6440,
 6460,
 6480,
 6506,
 6511,
 6535,
 6541,
 6553]

list_5 = []
for el in list_158:
    if el not in list_153:
        list_5.append(el)
list_5

[25442, 26877, 34119, 37932, 40081]

In [13]:
hh_ds.iloc[25442]

Пол, возраст                                Мужчина ,  25 лет , родился 16 июля 1993
ЗП                                                                        65000 руб.
Ищет работу на должность:                                        Инженер-программист
Город, переезд, командировки       Обнинск , не готов к переезду , готов к команд...
Занятость                                                           полная занятость
График                                                                   полный день
Опыт работы                        Опыт работы 3 года 2 месяца  Инженер-программи...
Последнее/нынешнее место работы                                       ИАТЭ НИЯУ МИФИ
Последняя/нынешняя должность                                             Программист
Образование и ВУЗ                  Высшее образование (Магистр) 2016  Обнинский и...
Обновление резюме                                                   06.04.2019 16:35
Авто                                                                      Не указано
Name: 25442, dtype: object

In [14]:
hh_ds.iloc[26877]

Пол, возраст                                Женщина ,  28 лет , родилась 25 мая 1990
ЗП                                                                        30000 руб.
Ищет работу на должность:                                          менеджер проектов
Город, переезд, командировки       Тюмень , не готова к переезду , не готова к ко...
Занятость                                                           полная занятость
График                                                                   полный день
Опыт работы                        Опыт работы 5 лет 5 месяцев  менеджер проектов...
Последнее/нынешнее место работы    Общество с ограниченной ответственностью Интер...
Последняя/нынешняя должность                                       менеджер проектов
Образование и ВУЗ                  Высшее образование 2014 Тюменский Государствен...
Обновление резюме                                                   22.04.2019 12:39
Авто                                                                      Не указано
Name: 26877, dtype: object

In [3]:
drop_data3 = pd.read_csv('data/comb_data_full.csv')

In [4]:
drop_data3.shape[0]

44744

In [5]:
drop_data3 = drop_data3.drop_duplicates()

In [6]:
drop_data3.shape[0]

44744